version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    volumes:
      - ./src/main/resources/dbinit:/docker-entrypoint-initdb.d
    expose:
      # Opens port 3306 on the container
      - '3306'
  tomcat:
    image: tomcat:8.5.47
    container_name: tomcat
    volumes:
      - ./target/servlet-test-web-xml-1.0-SNAPSHOT.war:/usr/local/tomcat/webapps/servlet.war
    ports:
      - '8082:8080'
    depends_on:
      - db